config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'

Rails.application.routes.draw do
  devise_for :users
  resources :events do 
    collection do 
      get :load_user_events
    end
  end
  resources :invitations do 
    collection do 
      get :approve_invitation
      get :reject_invitation
    end
  end
  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    
    has_and_belongs_to_many :users
    has_many :invitations

    

    validates_presence_of :event_title,:event_description,:start_time, :end_time
    validate :end_date_is_after_start_date
    #after_save :send_notifications
    #after_update :send_update_notification


    def send_notifications(users_list=[])
      puts "SEND NOTIFICATIONS:::\n"
      if users_list.empty?
        event_users = self.users 
      else
        event_users = User.where("id IN(?)", users_list)
      end
      Rails.logger.info "#{event_users.inspect} \n"
      event_users.each do |user|
        invitation_exists = self.invitations.where("user_id=?", user.id).first
        if invitation_exists.blank?
          invitation = self.invitations.build(event_id: self.id, user_id: user.id, aasm_state: "sent")
          invitation.save
          invitation.submit!
          NotificationMailer.event_success(self, user).deliver
        end
      end     
    end

    def send_update_notifications(users_list=[])
      event_users = User.where("id IN(?)", users_list)
      event_users.each do |user|
        NotificationMailer.event_updated(self, previous_changes, user).deliver
      end 
    end

    def accepted
      invitations.accepted.count
    end

    def rejected
      invitations.rejected.count
    end
    

    private
      def end_date_is_after_start_date
        return if end_time.blank? || start_time.blank?
      
        if end_time < start_time
          errors.add(:end_date, "cannot be before the start date") 
        end 
      end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :user
    belongs_to :event

    include AASM

    aasm do
      state :sent, initial: true
      state :inprocess
      state :accepted
      state :rejected
    
      event :submit do
        transitions from: :sent, to: :inprocess
      end
  
      event :approve do
        transitions from: [:inprocess],  to: :accepted
      end
  
      event :reject do
        transitions from: [:inprocess],  to: :rejected
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invitations
     
  
  has_and_belongs_to_many :events


  def accepted_invitations(date)
    events.where("start_time=?", date).includes(:invitations).where(invitations:{aasm_state:"accepted"})
  end
  def rejected_invitations(date)
    events.where("start_time=?", date).includes(:invitations).where(invitations:{aasm_state:"rejected"})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protected  
        def after_sign_in_path_for(resource)
        sign_in_url = new_user_session_url
        if request.referer == sign_in_url
            super
        else
            root_path
        end
        end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :users_list, only: [:new, :edit]

  def index
    @events = current_user.events
  end

  def new
    @event = Event.new
  end


  def create
    @event = Event.new(event_params)
    if @event.save
      @event.users << User.find(*params[:event_users])
      @event.send_notifications
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      existing_users = @event.users.collect(&:id)
      removed_users = existing_users - params[:event_users].map!(&:to_i)
      added_users = params[:event_users] - existing_users
      
      @event.send_update_notifications(existing_users) if !existing_users.empty?
      if !removed_users.empty?
        users = User.find(*removed_users)
        @event.users.delete(User.find(*removed_users))
      end
      @event.users << User.find(*added_users) if !added_users.empty?
      @event.send_notifications(added_users) if !added_users.empty?
      
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def users_list
    @all_users = User.all
  end

  def load_user_events
    if !params[:user_id].blank?
      @request_user = true
      user_id = params[:user_id]
      @user = User.find(user_id)
      @events = @user.events
    else 
      @request_user = false
      @events = Event.all
    end
  end

  private

  def event_params
  	params.require(:event).permit(:event_title, :event_description, :start_time, :end_time, :event_users, :user_id);
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :find_invitation, only: [:approve_invitation, :reject_invitation]

  def approve_invitation
    @invitation.approve! if (!@invitation.blank? && @invitation.inprocess?)
    redirect_to root_path
  end

  def reject_invitation
    @invitation.approve! if (!@invitation.blank? && @invitation.inprocess?) 
    redirect_to root_path
  end

  def find_invitation
    if params[:event_id].present? && params[:user_id].present?
      @event = Event.find_by_id(params[:event_id])
      @user = User.find_by_id(params[:user_id])
      @invitation = Invitation.where("user_id=? AND event_id=?", @user.id, @event.id).first
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def events_accepted date
      if date.blank?
        return 0
      else
       Event.where("start_time=?", date).includes(:users, :invitations).where(invitations: {aasm_state: 'accepted'}).count
      end
    end

    def events_rejected date 
      if date.blank?
       return 0
      else
        Event.where("start_time=?", date).includes(:users, :invitations).where(invitations: {aasm_state: 'rejected'}).count
      end
    end

    def date_id(date)
      date.to_s.gsub("-",'').to_i
    end
end

app/views/events/_form.html.haml
.col-6
  = simple_form_for @event do |f|
    = render 'shared/error_messages', object: @event
    = f.input :event_title
    = f.input :event_description
    = f.input :start_time, :as => :datetime_picker, input_html: { data: {date_options: {defaultDate: @event.start_time}}}
    = f.input :end_time, :as => :datetime_picker, input_html: { data: {date_options: {defaultDate: @event.end_time}}}
    = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
    %p
      = select_tag 'event_users', options_from_collection_for_select(User.all, :id, :email, @event.users.collect(&:id)), multiple: true, class: 'multiselectuser form-control'
    
    = f.button :submit
    = link_to "Back", events_path, class: 'btn btn-dark'
    %br

app/views/events/edit.html.haml
%h4
 Edit Event 
= render "form"

app/views/events/index.html.haml
%h3 Events  
%p
  = link_to "Add Event", new_event_path, class: "btn btn-secondary"
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Event Title
      %th{:scope => "col"} Start Time
      %th{:scope => "col"} End Time
      %th{:scope => "col"} Actions
  %tbody
    -@events.each do |event|
      %tr
      %th{:scope => "row"}=event.id
      %td=event.event_title
      %td=event.start_time
      %td=event.end_time
      %td
        = link_to "Edit", edit_event_path(event.id), class: "btn btn-secondary"
        = link_to "View", event_path(event.id), class: "btn btn-primary"
        = link_to "Delete", event_path(event.id),method: :delete, class: "btn btn-danger"
    

app/views/events/load_user_events.js.haml
-if @request_user
  $("#all_events").replaceWith("#{j render('/welcome/user_events')}");
-else
  $("#all_events").replaceWith("#{j render('/welcome/all_events')}");
  

app/views/events/new.html.haml
%h4
 Add Event 
= render "form"

app/views/events/show.html.haml
.container
  
  %p= @event.event_title
  %p= @event.event_description
  %p= @event.start_time
  %p= @event.end_time
  
  = link_to "Back", events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Event Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%=link_to "Home", root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "All Events", events_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete,  class:"nav-link") %>        
            <% else %>
              <%= link_to('Login', new_user_session_path, class:"nav-link")  %>  
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-error
    %a.close{"data-dismiss" => "alert"} ×
    %ul
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String)

app/views/welcome/_all_events.html.haml
#all_events
  = month_calendar events: @events do |date, events|
    = date
    %div 
      %span.badge.badge-primary
        =events.count

app/views/welcome/_event_actions.html.haml
- unless event.users.include?(current_user)
  = link_to edit_event_path(event.id) do
    %i.fa.fa-pencil-square-o{"aria-hidden" => "true"}
  = link_to edit_event_path(event.id), method: :delete do
    %i.fa.fa-trash{"aria-hidden" => "true"}

app/views/welcome/_user_events.html.haml
#all_events
  = month_calendar events: @events do |date, events|
    = date
    %div
      %h6
        No.of Events
        %span.badge.badge-secondary=events.count

      - accepted_events = @user.accepted_invitations(date)
      - rejected_events = @user.rejected_invitations(date)
      - calendar_date = date_id(date)
      = link_to accepted_events.count, "#", class: "badge badge-pill badge-success", onclick: "show_events('accepted',#{calendar_date});"
      = link_to rejected_events.count, "#", class: "badge badge-pill badge-danger", onclick: "show_events('rejected', #{calendar_date});"
      %div{class:"accepted_events_#{calendar_date}", style: "display:none;"}
        - accepted_events.limit(5).each do |event|
          = event.event_title
          = render "/welcome/event_actions", event: event

      %div{class:"rejected_event_#{calendar_date}", style: "display:none;"}
        - accepted_events.limit(5).each do |event|
          = event.event_title
          = render "/welcome/event_actions", event: event

app/views/welcome/index.html.haml
%h3
  Events Scheduled
- if current_user.present?
  .row
    
    .col-6
      = link_to "Add Event", new_event_path, class: "btn btn-secondary"
    .col-6
      = select_tag 'event_users', options_from_collection_for_select(User.all, :id, :email), :onchange => "select_user(this.value)", prompt: "All Users", class: "form-control"
    .col-12
      = render "all_events"
    